version: '3'
services:

  dt-duckiebot-interface:
    image: duckietown/dt-duckiebot-interface:daffy-arm32v7
    container_name: duckiebot-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  dt-roscore:
    image: duckietown/dt-ros-kinetic-base:daffy-arm32v7
    container_name: roscore
    restart: unless-stopped
    network_mode: host
    command: roscore

  dt-car-interface:
    image: duckietown/dt-car-interface:daffy-arm32v7
    container_name: car-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  dt-ros-websocket:
    image: duckietown/dt-rosbridge-websocket:daffy-arm32v7
    container_name: rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    volumes:
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  rpi-simple-server:
    image: duckietown/rpi-simple-server:master18
    container_name: simple-server
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
    working_dir: /data
