version: '3'
services:

  rpi-health:
    image: duckietown/rpi-health:master18
    container_name: health
    restart: always
    network_mode: host
    devices:
      - /dev/vchiq:/dev/vchiq
    volumes:
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  dt-device-online:
    image: duckietown/dt-device-online:daffy-arm32v7
    container_name: device-online
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      - /secrets:/secrets
      - /var/local:/var/local
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
