version: '3'
services:

  dt-device-health:
    image: duckietown/dt-device-health:ente-${ARCH-arm32v7}
    container_name: device-health
    restart: always
    network_mode: "host"
    devices:
      - /dev/vchiq:/dev/vchiq
    volumes:
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  dt-device-online:
    image: duckietown/dt-device-online:ente-${ARCH-arm32v7}
    container_name: device-online
    restart: always
    network_mode: "host"
    volumes:
      - /data:/data
      - /secrets:/secrets
      - /var/local:/var/local
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
