version: '3'
services:

  portainer:
    image: portainer/portainer:linux-arm
    container_name: portainer
    command: ["--host=unix:///var/run/docker.sock", "--no-auth"]
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dt-duckiebot-dashboard:
    image: duckietown/dt-duckiebot-dashboard:ente-${ARCH-arm32v7}
    container_name: duckiebot-dashboard
    restart: unless-stopped
    ports:
      - "8080:80/tcp"
    volumes:
      - compose-data:/var/www/html
      # generic duckietown data
      - /data:/robot/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  dt-device-loader:
    image: duckietown/dt-device-loader:ente-${ARCH-arm32v7}
    container_name: device-loader
    restart: on-failure
    network_mode: "host"
    environment:
      - EXCLUDE_RUN=DT18_00_basic
    volumes:
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      # duckietown data
      - /data:/data
      - /secrets:/secrets
      - /var/local:/var/local

  dt-device-proxy:
    image: duckietown/dt-device-proxy:ente-${ARCH-arm32v7}
    container_name: device-proxy
    restart: on-failure
    network_mode: "host"
    volumes:
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

volumes:
  compose-data:
